const { settingsStorage: storage } = settings

export const xhr = async (url, method, headers, body = '') => {
  // return stub
  try {
    storage.setItem('debug', `API: ${url} ${JSON.stringify(headers)} start`)
    res = await fetch({ url, method, headers, body })
    storage.setItem('debug', `API: ${url}` + res.status)
    if (!res.ok) return { status: res.status, error: res.body }

    const data = typeof res.body === 'string' ?  JSON.parse(res.body) : res.body
    return data
  } catch (error) {
    storage.setItem('debug', `JS ERROR: ${url} ${error}`)
    return { error: `JS error: ${error}`, status: '0' }
  }
}

export const store = {
  get id() { return storage.getItem('id') },
  get vin() { return storage.getItem('vin') },
  get code() { return storage.getItem('code') },
  get refresh_token() { return storage.getItem('refresh_token') },
  get access_token() { return storage.getItem('access_token') },
  get name() { return storage.getItem('name') },
  get eu() { return storage.getItem('eu') },
  get proxy() { return storage.getItem('proxy') },
  get vehicle() {
    return JSON.parse(storage.getItem('vehicle') || '{}')
  },
  set vehicle(data) {
    return storage.setItem('vehicle', JSON.stringify(data))
  },
  setItem: (item, value) => {
    return storage.setItem(item, value)
  },
  removeItem: item => {
    return storage.removeItem(item)
  },
  getItem: item => {
    return storage.getItem(item)
  },
}

const stub = {
 "id": 100021,
 "user_id": 800001,
 "vehicle_id": 99999,
 "vin": "TEST00000000VIN01",
 "color": null,
 "access_type": "OWNER",
 "granular_access": {
  "hide_private": false
 },
 "tokens": [
  "4f993c5b9e2b937b",
  "7a3153b1bbb48a96"
 ],
 "state": null,
 "in_service": false,
 "id_s": "100021",
 "calendar_enabled": true,
 "api_version": 54,
 "backseat_token": null,
 "backseat_token_updated_at": null,
 "charge_state": {
  "battery_heater_on": false,
  "battery_level": 42,
  "battery_range": 133.99,
  "charge_amps": 48,
  "charge_current_request": 48,
  "charge_current_request_max": 48,
  "charge_enable_request": true,
  "charge_energy_added": 48.45,
  "charge_limit_soc": 90,
  "charge_limit_soc_max": 100,
  "charge_limit_soc_min": 50,
  "charge_limit_soc_std": 90,
  "charge_miles_added_ideal": 202,
  "charge_miles_added_rated": 202,
  "charge_port_cold_weather_mode": false,
  "charge_port_color": "<invalid>",
  "charge_port_door_open": false,
  "charge_port_latch": "Engaged",
  "charge_rate": 0,
  "charger_actual_current": 0,
  "charger_phases": null,
  "charger_pilot_current": 48,
  "charger_power": 0,
  "charger_voltage": 2,
  "charging_state": "Disconnected",
  "conn_charge_cable": "<invalid>",
  "est_battery_range": 143.88,
  "fast_charger_brand": "<invalid>",
  "fast_charger_present": false,
  "fast_charger_type": "<invalid>",
  "ideal_battery_range": 133.99,
  "managed_charging_active": false,
  "managed_charging_start_time": null,
  "managed_charging_user_canceled": false,
  "max_range_charge_counter": 0,
  "minutes_to_full_charge": 0,
  "not_enough_power_to_heat": null,
  "off_peak_charging_enabled": false,
  "off_peak_charging_times": "all_week",
  "off_peak_hours_end_time": 360,
  "preconditioning_enabled": false,
  "preconditioning_times": "all_week",
  "scheduled_charging_mode": "Off",
  "scheduled_charging_pending": false,
  "scheduled_charging_start_time": null,
  "scheduled_departure_time": 1634914800,
  "scheduled_departure_time_minutes": 480,
  "supercharger_session_trip_planner": false,
  "time_to_full_charge": 0,
  "timestamp": 1692141038420,
  "trip_charging": false,
  "usable_battery_level": 42,
  "user_charge_enable_request": null
 },
 "climate_state": {
  "allow_cabin_overheat_protection": true,
  "auto_seat_climate_left": false,
  "auto_seat_climate_right": false,
  "auto_steering_wheel_heat": false,
  "battery_heater": false,
  "battery_heater_no_power": null,
  "bioweapon_mode": false,
  "cabin_overheat_protection": "On",
  "cabin_overheat_protection_actively_cooling": true,
  "climate_keeper_mode": "off",
  "cop_activation_temperature": "High",
  "defrost_mode": 0,
  "driver_temp_setting": 21,
  "fan_status": 0,
  "hvac_auto_request": "On",
  "inside_temp": 38.4,
  "is_auto_conditioning_on": true,
  "is_climate_on": false,
  "is_front_defroster_on": false,
  "is_preconditioning": false,
  "is_rear_defroster_on": false,
  "left_temp_direction": -293,
  "max_avail_temp": 28,
  "min_avail_temp": 15,
  "outside_temp": 36.5,
  "passenger_temp_setting": 21,
  "remote_heater_control_enabled": false,
  "right_temp_direction": -276,
  "seat_heater_left": 0,
  "seat_heater_rear_center": 0,
  "seat_heater_rear_left": 0,
  "seat_heater_rear_right": 0,
  "seat_heater_right": 0,
  "side_mirror_heaters": false,
  "steering_wheel_heat_level": 0,
  "steering_wheel_heater": false,
  "supports_fan_only_cabin_overheat_protection": true,
  "timestamp": 1692141038419,
  "wiper_blade_heater": false
 },
 "drive_state": {
  "active_route_latitude": 37.7765494,
  "active_route_longitude": -122.4195418,
  "active_route_traffic_minutes_delay": 0,
  "gps_as_of": 1692137422,
  "heading": 289,
  "latitude": 37.7765494,
  "longitude": -122.4195418,
  "native_latitude": 37.7765494,
  "native_location_supported": 1,
  "native_longitude": -122.4195418,
  "native_type": "wgs",
  "power": 1,
  "shift_state": null,
  "speed": null,
  "timestamp": 1692141038420
 },
 "gui_settings": {
  "gui_24_hour_time": false,
  "gui_charge_rate_units": "mi/hr",
  "gui_distance_units": "mi/hr",
  "gui_range_display": "Rated",
  "gui_temperature_units": "F",
  "gui_tirepressure_units": "Psi",
  "show_range_units": false,
  "timestamp": 1692141038420
 },
 "vehicle_config": {
  "aux_park_lamps": "NaPremium",
  "badge_version": 0,
  "can_accept_navigation_requests": true,
  "can_actuate_trunks": true,
  "car_special_type": "base",
  "car_type": "modely",
  "charge_port_type": "US",
  "cop_user_set_temp_supported": true,
  "dashcam_clip_save_supported": true,
  "default_charge_to_max": false,
  "driver_assist": "TeslaAP3",
  "ece_restrictions": false,
  "efficiency_package": "MY2021",
  "eu_vehicle": false,
  "exterior_color": "MidnightSilver",
  "exterior_trim": "Black",
  "exterior_trim_override": "",
  "has_air_suspension": false,
  "has_ludicrous_mode": false,
  "has_seat_cooling": false,
  "headlamp_type": "Premium",
  "interior_trim_type": "Black2",
  "key_version": 2,
  "motorized_charge_port": true,
  "paint_color_override": "19,20,22,0.8,0.04",
  "performance_package": "Base",
  "plg": true,
  "pws": true,
  "rear_drive_unit": "PM216MOSFET",
  "rear_seat_heaters": 1,
  "rear_seat_type": 0,
  "rhd": false,
  "roof_color": "RoofColorGlass",
  "seat_type": null,
  "spoiler_type": "None",
  "sun_roof_installed": null,
  "supports_qr_pairing": false,
  "third_row_seats": "None",
  "timestamp": 1692141038420,
  "trim_badging": "74d",
  "use_range_badging": true,
  "utc_offset": -25200,
  "webcam_selfie_supported": true,
  "webcam_supported": true,
  "wheel_type": "Apollo19"
 },
 "vehicle_state": {
  "api_version": 54,
  "autopark_state_v3": "ready",
  "autopark_style": "dead_man",
  "calendar_supported": true,
  "car_version": "2023.7.20 7910d26d5c64",
  "center_display_state": 0,
  "dashcam_clip_save_available": false,
  "dashcam_state": "Unavailable",
  "df": 0,
  "dr": 0,
  "fd_window": 0,
  "feature_bitmask": "15dffbff,0",
  "fp_window": 0,
  "ft": 0,
  "homelink_device_count": 3,
  "homelink_nearby": false,
  "is_user_present": false,
  "last_autopark_error": "no_error",
  "locked": true,
  "media_info": {
   "a2dp_source_name": "Pixel 6",
   "audio_volume": 2.6667,
   "audio_volume_increment": 0.333333,
   "audio_volume_max": 10.333333,
   "media_playback_status": "Playing",
   "now_playing_album": "KQED",
   "now_playing_artist": "PBS Newshour on KQED FM",
   "now_playing_duration": 0,
   "now_playing_elapsed": 0,
   "now_playing_source": "13",
   "now_playing_station": "88.5 FM KQED",
   "now_playing_title": "PBS Newshour"
  },
  "media_state": {
   "remote_control_enabled": true
  },
  "notifications_supported": true,
  "odometer": 15720.074889,
  "parsed_calendar_supported": true,
  "pf": 0,
  "pr": 0,
  "rd_window": 0,
  "remote_start": false,
  "remote_start_enabled": true,
  "remote_start_supported": true,
  "rp_window": 0,
  "rt": 0,
  "santa_mode": 0,
  "sentry_mode": false,
  "sentry_mode_available": true,
  "service_mode": false,
  "service_mode_plus": false,
  "smart_summon_available": true,
  "software_update": {
   "download_perc": 0,
   "expected_duration_sec": 2700,
   "install_perc": 1,
   "status": "",
   "version": " "
  },
  "speed_limit_mode": {
   "active": false,
   "current_limit_mph": 85,
   "max_limit_mph": 120,
   "min_limit_mph": 50,
   "pin_code_set": false
  },
  "summon_standby_mode_enabled": false,
  "timestamp": 1692141038419,
  "tpms_hard_warning_fl": false,
  "tpms_hard_warning_fr": false,
  "tpms_hard_warning_rl": false,
  "tpms_hard_warning_rr": false,
  "tpms_last_seen_pressure_time_fl": 1692136878,
  "tpms_last_seen_pressure_time_fr": 1692136878,
  "tpms_last_seen_pressure_time_rl": 1692136878,
  "tpms_last_seen_pressure_time_rr": 1692136878,
  "tpms_pressure_fl": 3.1,
  "tpms_pressure_fr": 3.1,
  "tpms_pressure_rl": 3.15,
  "tpms_pressure_rr": 3,
  "tpms_rcp_front_value": 2.9,
  "tpms_rcp_rear_value": 2.9,
  "tpms_soft_warning_fl": false,
  "tpms_soft_warning_fr": false,
  "tpms_soft_warning_rl": false,
  "tpms_soft_warning_rr": false,
  "valet_mode": false,
  "valet_pin_needed": true,
  "vehicle_name": "grADOFIN",
  "vehicle_self_test_progress": 0,
  "vehicle_self_test_requested": false,
  "webcam_available": true
 }
}
